apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backboneroles.iam-backbone.org
spec:
  group: iam-backbone.org
  names:
    kind: BackboneRole
    listKind: BackboneRoleList
    plural: backboneroles
    singular: backbonerole
    shortNames:
      - bbrole
      - bbroles
      - bbr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                roleName:
                  type: string
                permissions:
                  type: array
                  items:
                    type: string
              required:
                - roleName
