apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backboneusers.iam-backbone.org
spec:
  group: iam-backbone.org
  names:
    kind: BackboneUser
    listKind: BackboneUserList
    plural: backboneusers
    singular: backboneuser
    shortNames:
      - bbuser
      - bbusers
      - bbu
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                secretRef:
                  type: string
              required:
                - email
                - secretRef
